.TH PEGSOLITAIRE 6 "2019-01-01" "pegsolitaire 0.1.1" "User Commands"
.\" Please adjust this date whenever revising the manpage.
.
.SH NAME
pegsolitaire \- puzzle game for one player
.
.SH SYNOPSIS
.B pegsolitaire
.RI [ option ...]
.
.SH DESCRIPTION
.B pegsolitaire
is an educational puzzle game.
.PP
The goal of the game is to remove pegs from the board leaving a single peg in the
centre hole.
Pegs are removed from the board by making jumps.
You can jump over a peg with another peg horizontally or vertically, but not
diagonally.
.PP
When you jump over a peg, it is removed from the board.
Multiple jumps with one peg are allowed.
.
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.
.SH AUTHOR
pegsolitaire was written by Ben Asselstine.
.PP
This manual page was originally written by Barry deFreese <bddebian@comcast.net>
for the Debian and Ubuntu distributions.
