/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifndef PEGSOLITAIRE_INTERFACE_H
#define PEGSOLITAIRE_INTERFACE_H

#include <gtk/gtk.h>

GtkWidget* create_pegSolitaireWindow (void);
GtkWidget* create_pegSolitaireAboutDialog (void);

#endif // PEGSOLITAIRE_INTERFACE_H
