/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    g_object_ref (widget), (GDestroyNotify) g_object_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_pegSolitaireWindow (void)
{
  GtkWidget *pegSolitaireWindow;
  AtkObject *atko;
  GdkPixbuf *pegSolitaireWindow_icon_pixbuf;
  GtkWidget *pegSolitaireVBox;
  GtkWidget *pegSolitaireMenuBar;
  GtkWidget *gameMenuItem;
  GtkWidget *gameMenuItem_menu;
  GtkWidget *gameRestartMenuItem;
  GtkWidget *image27;
  GtkWidget *gameSeparatorMenuItem1;
  GtkWidget *gameEnglishMenuItem;
  GtkWidget *gameEnglishMenuItem_menu;
  GtkWidget *gameEnglishBeginnerMenuItem;
  GtkWidget *gameEnglishIntermediateMenuItem;
  GtkWidget *gameEnglishAdvancedMenuItem;
  GtkWidget *gameEuropeanMenuItem;
  GtkWidget *gameEuropeanMenuItem_menu;
  GtkWidget *gameEuropeanBeginnerMenuItem;
  GtkWidget *gameEuropeanIntermediateMenuItem;
  GtkWidget *gameEuropeanAdvancedMenuItem;
  GtkWidget *separator1;
  GtkWidget *gameQuitMenuItem;
  GtkWidget *helpMenuItem;
  GtkWidget *helpMenuItem_menu;
  GtkWidget *helpContentsMenuItem;
  GtkWidget *image28;
  GtkWidget *helpSeparatorMenuItem;
  GtkWidget *helpAboutMenuItem;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pegSolitaireWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (pegSolitaireWindow), _("Peg Solitaire"));
  gtk_window_set_position (GTK_WINDOW (pegSolitaireWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (pegSolitaireWindow), 400, 400);
  pegSolitaireWindow_icon_pixbuf = create_pixbuf ("pegsolitaire-icon.png");
  if (pegSolitaireWindow_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (pegSolitaireWindow), pegSolitaireWindow_icon_pixbuf);
      g_object_unref (pegSolitaireWindow_icon_pixbuf);
    }

  pegSolitaireVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (pegSolitaireVBox);
  gtk_container_add (GTK_CONTAINER (pegSolitaireWindow), pegSolitaireVBox);

  pegSolitaireMenuBar = gtk_menu_bar_new ();
  gtk_widget_show (pegSolitaireMenuBar);
  gtk_box_pack_start (GTK_BOX (pegSolitaireVBox), pegSolitaireMenuBar, FALSE, FALSE, 0);

  gameMenuItem = gtk_menu_item_new_with_mnemonic (_("_Game"));
  gtk_widget_show (gameMenuItem);
  gtk_container_add (GTK_CONTAINER (pegSolitaireMenuBar), gameMenuItem);

  gameMenuItem_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (gameMenuItem), gameMenuItem_menu);

  gameRestartMenuItem = gtk_image_menu_item_new_with_mnemonic (_("_Restart"));
  gtk_widget_show (gameRestartMenuItem);
  gtk_container_add (GTK_CONTAINER (gameMenuItem_menu), gameRestartMenuItem);
  gtk_widget_add_accelerator (gameRestartMenuItem, "activate", accel_group,
                              GDK_KEY_R, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image27 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image27);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (gameRestartMenuItem), image27);

  gameSeparatorMenuItem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (gameSeparatorMenuItem1);
  gtk_container_add (GTK_CONTAINER (gameMenuItem_menu), gameSeparatorMenuItem1);
  gtk_widget_set_sensitive (gameSeparatorMenuItem1, FALSE);

  gameEnglishMenuItem = gtk_menu_item_new_with_mnemonic (_("_English Board"));
  gtk_widget_show (gameEnglishMenuItem);
  gtk_container_add (GTK_CONTAINER (gameMenuItem_menu), gameEnglishMenuItem);

  gameEnglishMenuItem_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (gameEnglishMenuItem), gameEnglishMenuItem_menu);

  gameEnglishBeginnerMenuItem = gtk_menu_item_new_with_mnemonic (_("Beginner"));
  gtk_widget_show (gameEnglishBeginnerMenuItem);
  gtk_container_add (GTK_CONTAINER (gameEnglishMenuItem_menu), gameEnglishBeginnerMenuItem);

  gameEnglishIntermediateMenuItem = gtk_menu_item_new_with_mnemonic (_("Intermediate"));
  gtk_widget_show (gameEnglishIntermediateMenuItem);
  gtk_container_add (GTK_CONTAINER (gameEnglishMenuItem_menu), gameEnglishIntermediateMenuItem);

  gameEnglishAdvancedMenuItem = gtk_menu_item_new_with_mnemonic (_("Advanced"));
  gtk_widget_show (gameEnglishAdvancedMenuItem);
  gtk_container_add (GTK_CONTAINER (gameEnglishMenuItem_menu), gameEnglishAdvancedMenuItem);

  gameEuropeanMenuItem = gtk_menu_item_new_with_mnemonic (_("E_uropean Board"));
  gtk_widget_show (gameEuropeanMenuItem);
  gtk_container_add (GTK_CONTAINER (gameMenuItem_menu), gameEuropeanMenuItem);

  gameEuropeanMenuItem_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (gameEuropeanMenuItem), gameEuropeanMenuItem_menu);

  gameEuropeanBeginnerMenuItem = gtk_menu_item_new_with_mnemonic (_("Beginner"));
  gtk_widget_show (gameEuropeanBeginnerMenuItem);
  gtk_container_add (GTK_CONTAINER (gameEuropeanMenuItem_menu), gameEuropeanBeginnerMenuItem);

  gameEuropeanIntermediateMenuItem = gtk_menu_item_new_with_mnemonic (_("Intermediate"));
  gtk_widget_show (gameEuropeanIntermediateMenuItem);
  gtk_container_add (GTK_CONTAINER (gameEuropeanMenuItem_menu), gameEuropeanIntermediateMenuItem);

  gameEuropeanAdvancedMenuItem = gtk_menu_item_new_with_mnemonic (_("Advanced"));
  gtk_widget_show (gameEuropeanAdvancedMenuItem);
  gtk_container_add (GTK_CONTAINER (gameEuropeanMenuItem_menu), gameEuropeanAdvancedMenuItem);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (gameMenuItem_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  gameQuitMenuItem = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (gameQuitMenuItem);
  gtk_container_add (GTK_CONTAINER (gameMenuItem_menu), gameQuitMenuItem);

  helpMenuItem = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (helpMenuItem);
  gtk_container_add (GTK_CONTAINER (pegSolitaireMenuBar), helpMenuItem);

  helpMenuItem_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (helpMenuItem), helpMenuItem_menu);

  helpContentsMenuItem = gtk_image_menu_item_new_with_mnemonic (_("Contents"));
  gtk_widget_show (helpContentsMenuItem);
  gtk_container_add (GTK_CONTAINER (helpMenuItem_menu), helpContentsMenuItem);
  gtk_widget_add_accelerator (helpContentsMenuItem, "activate", accel_group,
                              GDK_KEY_F1, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image28 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image28);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (helpContentsMenuItem), image28);

  helpSeparatorMenuItem = gtk_separator_menu_item_new ();
  gtk_widget_show (helpSeparatorMenuItem);
  gtk_container_add (GTK_CONTAINER (helpMenuItem_menu), helpSeparatorMenuItem);
  gtk_widget_set_sensitive (helpSeparatorMenuItem, FALSE);

  helpAboutMenuItem = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (helpAboutMenuItem);
  gtk_container_add (GTK_CONTAINER (helpMenuItem_menu), helpAboutMenuItem);

  g_signal_connect ((gpointer) pegSolitaireWindow, "destroy",
                    G_CALLBACK (on_pegSolitaireWindow_destroy),
                    NULL);
  g_signal_connect ((gpointer) gameRestartMenuItem, "activate",
                    G_CALLBACK (on_gameRestartMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) gameEnglishBeginnerMenuItem, "activate",
                    G_CALLBACK (on_gameEnglishBeginnerMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) gameEnglishIntermediateMenuItem, "activate",
                    G_CALLBACK (on_gameEnglishIntermediateMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) gameEnglishAdvancedMenuItem, "activate",
                    G_CALLBACK (on_gameEnglishAdvancedMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) gameEuropeanBeginnerMenuItem, "activate",
                    G_CALLBACK (on_gameEuropeanBeginnerMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) gameEuropeanIntermediateMenuItem, "activate",
                    G_CALLBACK (on_gameEuropeanIntermediateMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) gameEuropeanAdvancedMenuItem, "activate",
                    G_CALLBACK (on_gameEuropeanAdvancedMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) gameQuitMenuItem, "activate",
                    G_CALLBACK (on_gameQuitMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) helpContentsMenuItem, "activate",
                    G_CALLBACK (on_helpContentsMenuItem_activate),
                    NULL);
  g_signal_connect ((gpointer) helpAboutMenuItem, "activate",
                    G_CALLBACK (on_helpAboutMenuItem_activate),
                    NULL);

  atko = gtk_widget_get_accessible (pegSolitaireWindow);
  atk_object_set_name (atko, _("Peg Solitaire"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pegSolitaireWindow, pegSolitaireWindow, "pegSolitaireWindow");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, pegSolitaireVBox, "pegSolitaireVBox");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, pegSolitaireMenuBar, "pegSolitaireMenuBar");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameMenuItem, "gameMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameMenuItem_menu, "gameMenuItem_menu");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameRestartMenuItem, "gameRestartMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, image27, "image27");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameSeparatorMenuItem1, "gameSeparatorMenuItem1");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEnglishMenuItem, "gameEnglishMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEnglishMenuItem_menu, "gameEnglishMenuItem_menu");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEnglishBeginnerMenuItem, "gameEnglishBeginnerMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEnglishIntermediateMenuItem, "gameEnglishIntermediateMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEnglishAdvancedMenuItem, "gameEnglishAdvancedMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEuropeanMenuItem, "gameEuropeanMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEuropeanMenuItem_menu, "gameEuropeanMenuItem_menu");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEuropeanBeginnerMenuItem, "gameEuropeanBeginnerMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEuropeanIntermediateMenuItem, "gameEuropeanIntermediateMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameEuropeanAdvancedMenuItem, "gameEuropeanAdvancedMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, gameQuitMenuItem, "gameQuitMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, helpMenuItem, "helpMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, helpMenuItem_menu, "helpMenuItem_menu");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, helpContentsMenuItem, "helpContentsMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, image28, "image28");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, helpSeparatorMenuItem, "helpSeparatorMenuItem");
  GLADE_HOOKUP_OBJECT (pegSolitaireWindow, helpAboutMenuItem, "helpAboutMenuItem");

  gtk_window_add_accel_group (GTK_WINDOW (pegSolitaireWindow), accel_group);

  return pegSolitaireWindow;
}

GtkWidget*
create_pegSolitaireAboutDialog (void)
{
  GtkWidget *pegSolitaireAboutDialog;
  const gchar *authors[] = {
    "Ben Asselstine",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GdkPixbuf *pegSolitaireAboutDialog_logo_pixbuf;

  pegSolitaireAboutDialog = gtk_about_dialog_new ();
  gtk_window_set_destroy_with_parent (GTK_WINDOW (pegSolitaireAboutDialog), TRUE);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (pegSolitaireAboutDialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (pegSolitaireAboutDialog), _("Peg Solitaire"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (pegSolitaireAboutDialog), _("This software is dedicated\n to Mothers everywhere."));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (pegSolitaireAboutDialog), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (pegSolitaireAboutDialog), translators);
  pegSolitaireAboutDialog_logo_pixbuf = create_pixbuf ("pegsolitaire-icon.png");
  gtk_about_dialog_set_logo (GTK_ABOUT_DIALOG (pegSolitaireAboutDialog), pegSolitaireAboutDialog_logo_pixbuf);

  g_signal_connect ((gpointer) pegSolitaireAboutDialog, "close",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pegSolitaireAboutDialog, pegSolitaireAboutDialog, "pegSolitaireAboutDialog");

  return pegSolitaireAboutDialog;
}

