/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifndef PEGSOLITAIRE_SUPPORT_H
#define PEGSOLITAIRE_SUPPORT_H

#include <gtk/gtk.h>

/*
 * This function returns a widget in a component created by Glade.
 * Call it with the toplevel widget in the component (i.e. a window/dialog),
 * or alternatively any widget in the component, and the name of the widget
 * you want returned.
 */
GtkWidget*  lookup_widget              (GtkWidget       *widget,
                                        const gchar     *widget_name);

#endif // PEGSOLITAIRE_SUPPORT_H
